version: '3'

services:

  master:
    image: locustio/locust
    expose:
      - "8089"
    volumes:
      - ./:/mnt/locust
    environment:
      LOCUST_HOST: http://127.0.0.1:8080
      LOCUST_USERS: 100
    command: -f /mnt/locust/locustfile.py --master -r 1
    network_mode: host

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host localhost
    network_mode: host